type Auth {
  accessToken: String!
  refreshToken: String!
}

input SignInInput {
  email: String!
  password: String!
}

input RefreshTokenInput {
  refreshToken: String!
}

extend type Mutation {
  SignIn(input: SignInInput!): Auth
  RefreshToken(input: RefreshTokenInput!): Auth
}
